name: Build and Test
on:
  push:
    branches:
      - dev
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v1

      #      - name: Tesing
      #        run: |
      #          go test -v .

      - name: Build binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o release/linux/amd64/helloadmin

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.9
        with:
          name: itbing/helloadmin
          username: itbing
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile.linux.amd64

      - name: Update the API service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USERNAME }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: ${{ secrets.DEV_SSH_PORT }}
          #          script: whoami
          script_stop: true
          script: |
            cd golang/helloadmin && docker-compose pull && docker-compose up -d